security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_PDG: [ROLE_BU, ROLE_USER]
        ROLE_BU: [ROLE_USER]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login        # route de la page login
                check_path: app_login        # route pour vérifier le login (submit)
                enable_csrf: true
            logout:
                path: app_logout
                target: app_login
            two_factor:
                auth_form_path: app_2fa_login         # route affichant formulaire 2FA
                check_path: app_2fa_login_check       # route vérifiant code 2FA

    access_control:
        # Le PDG peut accéder à tout ce qui commence par /admin
        - { path: ^/admin, roles: ROLE_PDG }

        # Le BU accède au module projet (ex: /project) et aux alertes / évolutions (ex: /bu)
        - { path: ^/project, roles: ROLE_BU }
        - { path: ^/bu, roles: ROLE_BU }

        # Le collaborateur accède uniquement à ses tâches, notifications, compte
        - { path: ^/task, roles: ROLE_USER }
        - { path: ^/notification, roles: ROLE_USER }
        - { path: ^/account, roles: ROLE_USER }

        # Pour le dashboard, tous les utilisateurs connectés
        - { path: ^/dashboard, roles: ROLE_USER }

        # Accès à la page 2FA uniquement pendant le processus 2FA
        - { path: ^/2fa, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }

        # Déconnexion accessible publiquement
        - { path: ^/logout, roles: PUBLIC_ACCESS }
