# config/services.yaml
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\EventListener\TrustedDeviceListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    App\EventListener\TrustedDeviceBypassListener:
        tags:
            - { name: kernel.event_listener, event: scheb_two_factor.require, method: onRequire2FA }

    trusted_device:
        class: App\Security\Condition\TrustedDeviceCondition
        tags:
            - { name: 'scheb_two_factor.condition', key: 'trusted_device' }